services:
  - type: web
    name: todo-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run test:db && npm run db:migrate && npm run db:seed:categories && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
    autoDeploy: true

databases:
  - name: todo-db
    databaseName: todo_db
    user: todo_user
    plan: free
    ipAllowList: []
